# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-google-tag-manager

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Hire Yap'
description: 'This is Yap Shiao Shyan personal website'
# permalink: pretty
logo: "https://github.com/identicons/mryap.png"

# Permalink format (/blog/ is ignored for pages)
permalink: /blog/:title

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/
  #Service: /service/
  #Hire: /hire/
  Categories: /categories/
  

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My scrappy notes on all things data analytics, web design and developments, data science"
    feature_text: |
      Notes, Updates, News
    feature_image: "https://picsum.photos/2560/600?image=866"
    
# GTM
google:
  tag_manager:
    container_id: GTM-WXZ576M   

#google_analytics: 'UA-126272083-1'
