# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-google-tag-manager

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Product Marketing Analytics'
description: 'This is my new website'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/
  #Service: /service/
  Hire: /hire/
  

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My scrappy notes on all things data analytics"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
    
# GTM
google:
  tag_manager:
    container_id: GTM-WXZ576M   

#google_analytics: 'UA-126272083-1'
