[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/"
  to = "https://www.testandoptimize.com/"
  status = 301
  force = true
  headers = {X-From = "Netlify"}
